site_name: 'CoderDojo TC Thunkable Resources'
nav:
  - Home: index.md
  - Basics:
      - Introduction: basics/basics-intro.md
      - 01 - Getting Started: basics/basics-01-get-started.md
      - 02 - App Designer: basics/basics-02-app-designer.md
      - 03 - App Blocks Editor: basics/basics-03-blocks-editor.md
      - 04 - Testing and Saving an App: basics/basics-04-testing-saving.md
      - 05 - More Resources: basics/basics-05-more-resources.md
  - Lesson 01 - Big Red Button:
      - 01 - Introduction: lesson01/l01-01-intro.md
      - 02 - Adding Button: lesson01/l01-02-adding-button.md
      - 03 - Programming Button: lesson01/l01-03-programming-button.md
      - 03b - Extra Button Actions: lesson01/l01-03b-button-actions.md
  - Technovation: technovation.md
  - Contribute: contribute.md
  - Contacts: contacts.md

repo_name: 'Thunkable'
repo_url: 'https://github.com/CoderDojoTC/thunkable'
edit_uri: 'blob/master/docs'
copyright: 'All content is licensed under Creative Commons Sharealike non-commercial with attribution'
theme:
  name: material
  logo: img/coderdojo-logo.jpg
  favicon: img/favicon.ico
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - attr_list
  - pymdownx.details
